name: Regenerate POT file (translatable strings)
on:
  schedule:
    # 0:30 UTC / 08:30 AM HKT
    - cron: "30 0 * * 0" 
  workflow_dispatch:

jobs:
  regenerate-pot-file:
    name: Regenerate POT file
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        branch: ["develop-next"]
    permissions:
      contents: write

    steps:
        - name: Checkout
          uses: actions/checkout@v5
          with:
            ref: ${{ matrix.branch }}

        - name: Setup Python
          uses: actions/setup-python@v6
          with:
            python-version: "3.13"

        - name: Run script to update POT file
          run: |
            bash ${GITHUB_WORKSPACE}/.github/helper/update_pot_file.sh
          env:
            GH_TOKEN: ${{ secrets.RELEASE_TOKEN }}
            BASE_BRANCH: ${{ matrix.branch }}
